name: boltz
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.12
  - cuda=12.6

  - lightning
  - numpy<2.0
  - hydra-core=1.3
  - rdkit=2024.9.6
  - dm-tree=0.1.8
  - requests=2.32
  - types-requests
  - pandas>=2.2.2,<3.0
  - einops=0.8
  - einx=0.3
  - mashumaro=3.14
  - modelcif=1.2
  - wandb>=0.18
  - click=8.1
  - pyyaml=6.0
  - biopython=1.84
  - scipy>=1.13,<2.0
  - numba>=0.61
  - gemmi>=0.6.5
  - scikit-learn>=1.6,<2.0
  - chembl_structure_pipeline>=1.2.2

  - ruff
  - mypy
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu126
      - -f https://data.pyg.org/whl/torch-2.6.0+cu126.html
      - torch==2.6.0+cu126
      - cuequivariance-torch
      - cuequivariance-ops-torch-cu12

      - fairscale==0.4.13