name: boltz
channels:
  - pytorch
  - nvidia/label/cuda-11.8.0
  - conda-forge
dependencies:
  - python>=3.9
  - pytorch>=2.2=*cuda*
  - pytorch-cuda=11.8
  - cuda
  - numpy<2.0
  - hydra-core=1.3
  - pytorch-lightning=2.4
  - rdkit==2024.3.2
  - dm-tree=0.1.8
  - requests=2.32
  - pandas=2.2
  - einops=0.8
  - einx=0.3
  - mashumaro=3.14
  - modelcif=1.2
  - wandb
  - click=8.1
  - pyyaml=6.0
  - biopython=1.84
  - scipy<2.0
  - pip
